#처음 이용할시 jsessionid가 붙지 않도록 설정

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie

spring:
  messages:
    basename: messages, errors
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ploc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

file:
  dir: C:/Users/Woo/Desktop/공부/spring/project/ploc/file/

logging:
  level:
    com.example.ploc: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace